### ISSUE TITLE
Running on remote machine: vimcom does not load

### ISSUE THREAD

**Issue by mbojan** [jalvesaq/VimCom#20]
I'm trying to set up vimrplugin+tmux+vimcom on a server (no GUI) to be able to work remotely. I have installed some minimal X server so that vim could communicate with R. However, when I start R from vim launched in tmux I am getting an error that vimcom package was not loaded. And vimcom is installed and avaiable to R (I can load it manually via `library()`). How can I debug this?

More detailed steps (the server runs Ubuntu 14.04 64bit):

1. I have installed vim with support of `--servername` option.
2. I have installed development version of "vim-r-plugin" from GitHub
3. I have installed development version of "vimcom" from GitHub
4. I have installed minimal X: `xserver-xorg-core` and `libx11-dev`.
5. I launch `tmux`
6. Within `tmux` I launch vim with `vim --servername VIM file.R`
7. Launching R with `\rf`

At this moment R console opens on the right OK, but at the bottom of vim there is a message 
`waiting vimcom loading...`
and then
`Package vimcom wasn't loaded yet` (or something like that, it flashes quickly)

I can send commands to R, but I cannot open help pages with `:Rhelp`, so seems the communication between vim and R goes only one way (vim -> R).

Can you help and suggest what should I check in my setup?

Thanks!

**Comment by jalvesaq** [comment]
@mbojan did you solve the problem?

**Comment by mbojan** [comment]
Yes, in a sense... I think the issue was that I had some mismatch between versions of vimcom and vimrplugin. When I updated both to latest version the issue vanished.

Thanks for your help. This can be closed

**Comment by jalvesaq** [comment]
Thanks for your feedback.
