### ISSUE TITLE
tmux.conf: can't establish current session

### ISSUE THREAD

**Issue by mistachie777** [jalvesaq/VimCom#25]
I am currently running the development versions of both vimcom and the vim-r-plugin in Linux using vim from the terminal.  Whenever I launch R from within vim (<leader>rf), I always see an error that tmux can't establish the environment.  When I open the tmux.conf file in /tmp, it appears that in all of the lines which cause the error (3, 4, 16) the -g switch is not used, but I do not know if that is intentional.

R behaves as though vimcom is not loaded, meaning I can't open help entries or update the object browser (as described in the documentation).  This is happening despite the fact that library(vimcom) is in my .Rprofile, and I have launched vim with the --servername option.  If I use sessionInfo() to check if vimcom is loaded, it does show it.  

I have also been able unable to debug much at all because vimcom produces no output on the R console, even when I use vimcom.verbose=4 in my .Rprofile.

**Comment by jalvesaq** [comment]
Does your Vim really has the 'clientserver' feature? That is, what is the output of:
```vim
:echo has("clientserver")
```

What happens if you start Tmux before Vim? Example:
```sh
tmux
vim --servername VIM example.R
```

You could also try [Neovim](https://github.com/neovim/neovim) + [Nvim-R](https://github.com/jalvesaq/Nvim-R) + [nvimcom](https://github.com/jalvesaq/nvimcom).

**Comment by mistachie777** [comment]
Running :echo has("clientserver") returns 1, so that's definitely enabled.  When I run tmux first, it produces the same error ("waiting for reply" when launching help, "no vimcom port found" when opening the object browser).  And vimcom still fails to produce any output on the R console.

I have tried to use neovim before, but unfortunately several other vim plugins I use are currently incompatible with it (i.e. powerline, YouCompleteMe).

**Comment by jalvesaq** [comment]
The vimcom package will load, but will not run the TCP server if either `VIMRPLUGIN_TMPDIR` or `VIMRPLUGIN_COMPLDIR`  environment variable is not set. In this case, vimcom will silently return while running either `.onLoad()` or `.onAttach()`. Do you have a `~/.tmux.conf` and did you unset these variables there? Both commands below should return something in R:

```r
Sys.getenv("VIMRPLUGIN_TMPDIR")
Sys.getenv("VIMRPLUGIN_COMPLDIR")
```

**Comment by mistachie777** [comment]
This is my .tmux.conf.  I don't think anything in there should be affect the value of those variables.
```
# Lines added by the Vim-R-plugin command :RpluginConfig (2014-Oct-14 16:28):
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix
# Set "status on" if you usually create new Tmux windows
set -g status off
set-window-option -g mode-keys vi
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g mode-mouse on
set -g mouse-select-pane on
set -g mouse-resize-pane on
```
However, when I check the values of `VIMRPLUGIN_TMPDIR` and `VIMRPLUGIN_COMPDIR` with `Sys.getenv`, the `TMPDIR` value is correct, while the `COMPDIR` value is blank.  I tried to set the `COMPDIR` variable using `let vimrplugin_compdir = ~/.cache/Vim-R-plugin` in my `.vimrc` as described in the documentation, but that doesn't change the value when I check with `Sys.getenv()`.  

I also tried to check the value of both `g:vimrplugin_tempdir` and `g:vimrplugin_compldir` and they both initially produced errors.  I manually set them in my `.vimrc` and now I can see the values when I run vim, but `COMPDIR` is still blank and the problems still persist.

**Comment by jalvesaq** [comment]
The name of the variable is `VIMRPLUGIN_COMPLDIR` and not `VIMRPLUGIN_COMPDIR`.

**Comment by mistachie777** [comment]
Oops, I mistyped it on here, but when I checked it in R I spelled it right.  Sorry for the confusion!

**Comment by jalvesaq** [comment]
It should be working. Does it exist in Vim? You can check with:

```vim
echo $VIMRPLUGIN_COMPLDIR
```

If it exists, I don't know what might be wrong. The only other thing that I can imagine is that you have the plugin installed in two places, like one that you have installed manually and other that you installed using a plugin manager.

**Comment by mistachie777** [comment]
It turns out I did have an ancient copy that I manually installed and completely forgot about.  As soon as I deleted it and reinstalled the plugin with Vundle, everything worked perfectly.  Thank you so much for your help!

**Comment by Figuera** [comment]
My VIMRPLUGINS_COMPLDIR is empty, I tryed to set to ~/.cache/Vim-R-plugin but no success, any ideas? 

By the way, I have already remove and reinstalled all plugins, just in case, but that did not help.

**Comment by jalvesaq** [comment]
It seems to be the same problem reported in this issue. You can check what files Vim is reading with this command:
```
vim --startuptime /tmp/vim_startup_time script.R
```
Then, you can look at `/tmp/vim_startup_time` to check if the files listed at [r-plugin-files](http://www.lepem.ufc.br/jaa/r-plugin.html#r-plugin-files) are all being read from the same directory (which will be `~/.vim` if you have installed the plugin using the vimball).

**Comment by Figuera** [comment]
You were right, there was some ambiguity between two versions installed. Since one of them was a bit hidden I was not able to find it in my first attempt, The command you suggest really helped.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
