### ISSUE TITLE
Vimcom port not found (again ?)

### ISSUE THREAD

**Issue by Figuera** [jalvesaq/VimCom#26]
I am getting the classic Vimcom port not found error even when I:

- Start R from Vim
- Both R-plugin and Vimcom are version 1.2.6
- Vimcom is loaded in R

I dont know what to do.

**Comment by jalvesaq** [comment]
Please, read [r-plugin-nox](http://www.lepem.ufc.br/jaa/r-plugin.html#r-plugin-nox) and also see if the comments at this issue are helpful: https://github.com/jalvesaq/VimCom/issues/25

**Comment by jalvesaq** [comment]
This will be fixed by:
https://github.com/jcfaria/Vim-R-plugin/tree/jobchannel
https://github.com/jalvesaq/VimCom/tree/jobchannel

**Comment by jalvesaq** [comment]
This issue should be fixed now.
