### ISSUE TITLE
Folders with UTF-8 characters 

### ISSUE THREAD

**Issue by galadude** [jalvesaq/VimCom#29]
I get the following error message when I start the R consol from Vim-R-plugin:
>    error: cannot change working directory

In the error message my folder appears with a Ã¦ instead of an æ. I guess there's some problem with reading non-ascii character, is there anyway around this?

**Comment by jalvesaq** [comment]
I can reproduce the bug on Windows when I have in my vimrc:

```
set encoding=utf-8
```

After the startup is complete, R can automatically detect the encoding of a string. Example:

```
> Encoding("abc")
[1] "unknown"
> Encoding("El niño")
[1] "latin1"
> Encoding("Where is my ☂?")
[1] "UTF-8"
```

But it is not detected while loading vimcom.

**Comment by jalvesaq** [comment]
@galadude Are you using Windows?

**Comment by galadude** [comment]
Yes I'm on Windows. I've figured out that R is to blame, and not vimcom or vim-r-plugin. R wasn't sourcing files with the proper encoding. I added 

>options(encoding = "utf-8")

to my .Rprofile, and now everything is working perfectly. Thanks for your help and merry Christmas!
