### ISSUE TITLE
Junk showing up in the R window

### ISSUE THREAD

**Issue by scottstanfield** [jalvesaq/VimCom#30]
1. I'm not sure if this is VimCom issue. If not, please close.
2. I also don't have a simple set of steps to reproduce yet.

That being said, I'm getting a lot of "junk", for lack of a better term, showing up in the R window. It's the lines beginning with `0gn`. They look like artifacts of temporary paths that might be used behind the scenes to link vim + tmux + R.

![R window capture](http://cl.ly/ev4Q/Image%202016-01-22%20at%203.31.49%20PM.png)

Is this to be expected?

**Comment by jalvesaq** [comment]
No, it is not expected. Even if you have `options(vimcom.verbose = 2)` in your `.Rprofile` the extra output should be intertwined with the normal output and not mixed with it. The string looks like either `$VIMRPLUGIN_SECRET` or `$VIMINSTANCEID`. You can check in R whether this is the case or not:

```r
Sys.getenv("VIMINSTANCEID")
Sys.getenv("VIMRPLUGIN_SECRET")
```

**Comment by scottstanfield** [comment]
Checking...I should have asked: is there a way to turn it off? 

I have `options(vim.com.verbose = 1)` in my local `.Rprofile`. Perhaps that is the source of the confusion.

**Comment by scottstanfield** [comment]
```
> Sys.getenv("VIMINSTANCEID")
[1] "Usersscottprojectse9reposthoriumthoriumRfAf0on4s5ahg5s16McTVrw"
> Sys.getenv("VIMRPLUGIN_SECRET")
[1] "6Y2D7HpfD5wOkX9blnncQ"
>
```

**Comment by scottstanfield** [comment]
Running `options(vim.com.verbose = 0)` cut down on most of the messages.

I'll close this for now as it's probably not a bug with the code. Just with the way I have it connected. I will reopen it if persists.

**Comment by jalvesaq** [comment]
`vimcom.verbose = 1` should output just one message at startup: "vimcom [version] loaded".
