### ISSUE TITLE
VimCom works in Tmux but not outside it

### ISSUE THREAD

**Issue by jrlil** [jalvesaq/VimCom#31]
I have installed the latest released versions of VimCom and Vim-R-Plugin on Arch Linux. The plugin seems to run well in a Tmux session, but VimCom does not load when started in a terminal ("The package vimcom wasn't loaded yet."). I use Termite terminal and also tested xterm, same result.

I really dont't want to use Tmux since I use a tiling window manager and learning as well as configuring Tmux to my liking would take too much time and effort and only complicates using the plugin.

**Comment by jalvesaq** [comment]
Could you try [Nvim-R](https://github.com/jalvesaq/Nvim-R) + [nvimcom](https://github.com/jalvesaq/nvimcom)? Please, see: https://github.com/jalvesaq/Nvim-R/issues/25

**Comment by jalvesaq** [comment]
Note: Nvim-R does not need Tmux.

**Comment by jrlil** [comment]
I appreciate the prompt response. When Nvim-R is started in Neovim, the Neovim session is split into two windows, one of them running R inside Neovim. I was hoping it will open a new terminal window running just R, but I guess it has more todo with Neovim and Termite behavior. It's still much simpler than having Tmux in between.

Thank you for your help and for creating this wonderful software!

**Comment by jalvesaq** [comment]
If you need R in a separated terminal you should put in your `init.vim`:
```vim
let R_in_buffer = 0
```
R will, then, run in a Tmux session. However, note that `termit` is not supported.

**Comment by jalvesaq** [comment]
This issue should be fixed now.
