### ISSUE TITLE
error when installing (windows)

### ISSUE THREAD

**Issue by galadude** [jalvesaq/VimCom#32]
I got the following error when trying to install VimCom:

```
Error in namespaceExport(ns, exports) : 
  ej defineret eksport: vim.list.args, vim.srcdir, vim.plot, vim.interlace.rnoweb, vim.interlace.rrst, vim.print, vim.names, etags2ctags, vim.interlace.rmd
```

Excuse the danish. 

Edit: The danish means "Undefined export: vim.list.args, vim.srcdir, etc".

**Comment by jranke** [comment]
Why not try to translate the Danish? Kind regards, Johannes

**Comment by galadude** [comment]
I've edited to include a translation. The full error can be found [here](https://gist.github.com/galadude/a56de81aded840271946). I've added a comment translating the important bits.

**Comment by jranke** [comment]
Ah, clearer now. However,I do not understand the reason for the error. Maybe Jakson @jalvesaq has an idea...

**Comment by jalvesaq** [comment]
I just tested the installation on Windows, and there was no problem. Could you, please, give details about your system (R, Rtools, etc)? Where did you get vimcom and what commands are you issuing?

**Comment by galadude** [comment]
I uninstalled version 1.2-6, to see if that would help.
I think it's an issue with devtools, and not vimcom. Whenever I use `devtools::install_github` i now get the error 

```
"C:/PROGRA~1/R/R-32~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD  \
  INSTALL  \
  "C:/Users/vhg505/AppData/Local/Temp/Rtmp0gcBlq/devtools17c82e2e25ae/cran-colorspace-76a3b1f"  \
  --library="C:/Program Files/R/R-3.2.2/library" --install-tests 

Error in library(vimcom) : no packages named 'vimcom'
```

I've checked my site file, and it's now empty. I'm trying to look for a test, that's coursing this.

**Comment by jalvesaq** [comment]
I can't help with this issue because I don't use devtools. @jimhester  had suggested mentioning devtools in the README.md, and @mllg had made a pull request integrating devtools in vimcom. Perhaps one of them can help you.

**Comment by jimhester** [comment]
@galadude You must have `library(vimcom)` in your `.Rprofile` and if you are still having problems installing VimCom that is why it is failing.

I would suggest you put all code in your `.Rprofile` within a interactive block so they are only executed in interactive sessions. e.g.

```r
if (interactive()) {
  library(vimcom)
}
```

**Comment by galadude** [comment]
@jimhester: I thought about this. It turns out I was changing the wrong `.Rprofile`. Thank you for the help!
