### ISSUE TITLE
Second session starts on same folder as running session

### ISSUE THREAD

**Issue by zeloff** [jalvesaq/VimCom#35]
I load `vimcom` in `.Rprofile` inside an `if (interactive)` block. Vim isn't involved in any of this.

If I start an R session on directory `~/A`, leave it running, and then open a different terminal and start a new session on directory `~/B`, the second session is also started on directory `~/A`, i.e., `getwd()` returns `~/A` on both sessions. I don't think this was the default behaviour... Can you confirm this?
Thanks

**Comment by jalvesaq** [comment]
It's no longer necessary to put `library(vimcom)` in the Rprofile. What happens if you do not load vimcom in your Rprofile?

**Comment by zeloff** [comment]
Removing `library(vimcom)` from `.Rprofile` solves the problem. Closing the issue, sorry for the noise.
