### ISSUE TITLE
\rf

### ISSUE THREAD

**Issue by cjieming** [jalvesaq/VimCom#36]
Hi I recently tried Nvim-R on Linux, Vim 8.0 and R 3.4. I installed everything and I could do (finally) \rf, but I got an error message: 
During startup - Warning messages:
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found 
> nvimcom:::nvim.buildomnils("datasets")
Error in loadNamespace(name) : there is no package called ‘nvimcom’
Calls: ::: ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

I tried including the following in my .Rprofile in my home directory:
if(Sys.getenv("NVIMR_TMPDIR") == ""){
       options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods"))
   } else {
       options(defaultPackages = c("utils", "grDevices", "graphics", "stats", "methods", "nvimcom"))
}

But nothing seems to work. Any help would be appreciated!
Thank you!

**Comment by mschilli87** [comment]
Did you install the `nvimcom` R package?
You can ceck by running something like

```sh
R --slave <<< library(nvimcom)
```

from your shell or

```r
"nvimcom" %in% installed.packages()
```

in an R session.

I'm using neovim and I installed Nvim-Rand via vim-plug and for me running `\rf` automatically installed the nvimcom library for R.
Maybe that's different with vim or maybe something went wrong during the installation (permission error?).

If you need more help, knowing which distribution you are on would probablt help, too.

**Comment by cjieming** [comment]
Hi @mschilli87 , thanks for your reply!

I am on these distributions:
R version 3.4.0 (2017-04-21)
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  2 2018 15:23:41)
LINUX: Red Hat Enterprise Linux Server release 6.6

I ran <"nvimcom" %in% installed.packages()> in an R session and got <[1] TRUE>
So I assume nvimcom's been installed, but just not loaded when I ran \rf for some reason... 

I have been trying for about 2 days now, so any help would be greatly appreciated! Thank you!

**Comment by mschilli87** [comment]
@cjieming: Sorry, but I'm out of ideas right now. Maybe @jalvesaq can help you to further track this down.

**Comment by mschilli87** [comment]
@cjieming: Actually, could this already be solved by https://github.com/jalvesaq/Nvim-R/commit/24960c269aff041bba6b075e8d63b32e23a32ecc (see https://github.com/jalvesaq/Nvim-R/issues/269)?

**Comment by jalvesaq** [comment]
The nvimcom package should be automatically installed when R is started with the command `<LocalLeader>rf`. No configuration should be required in the .Rprofile, .bashrc, etc. You should just install Nvim-R. If using vim-plug, this should be enough:
```vim
Plug 'jalvesaq/Nvim-R'
```
So, the first thing that you could try would be to remove any R related configuration of your `~/.bashrc` and `~/.profile`, and Nvim-R related configuration from your `~/.Rprofile`.

This VimCom package is dead. So, any issues should be reported at https://github.com/jalvesaq/Nvim-R/issues
